### ISSUE TITLE
PublicTransportTravelCosts ne fonctionne pas sur Mac

### ISSUE THREAD

**Issue by matt-gau** [mobility-team/mobility#121]
@FlxPo 
Les distances et durée retournées lors de la création de pub_trans_travel_costs sont nulles (valeurs NA). En remontant au fichier R et en ajoutant [ici](https://github.com/mobility-team/mobility/blob/b4d0d0fc72f2239ab8b28afc1e0c47d764a54d3c/mobility/R/prepare_public_transport_costs.R#L164) ce code :
```
info(logger, "Affichage de tt retourné par gtfs_traveltimes")
    info(logger, tt[, .(duration)])
    info(logger, names(tt))
```
j'obtiens dans la console spyder ce qui est dans le fichier txt ci-dessous, puis si j'affiche la meme chose mais [trois lignes plus tard](https://github.com/mobility-team/mobility/blob/b4d0d0fc72f2239ab8b28afc1e0c47d764a54d3c/mobility/R/prepare_public_transport_costs.R#L169) je n'obtiens que des vecteurs c(NA,NA...) ou des numeric(0).
 
[console affichage tt.txt](https://github.com/user-attachments/files/16177403/console.affichage.tt.txt)

**Comment by FlxPo** [comment]
Peux tu récupérer les modifications de la branche `add-switzerland` et refaire test tests ? Il y a quelques modifications qui pourraient régler le problème.

**Comment by Mind-the-Cap** [comment]
Fonctionne maintenant !
