### ISSUE TITLE
Mettre en place une fonction pour calculer les émissions carbones associées aux déplacements

### ISSUE THREAD

**Issue by louisegontier** [mobility-team/mobility#19]

**Comment by louisegontier** [comment]
Mise en place d'une fonction pour récupérer les facteurs ADEME et les appliquer à la table trips en sortie du trip sampler : https://github.com/mobility-team/mobility/commit/d3ef88e7d46a2cfe6ba2f12bc152d50eb7c88bda

TO DO : 

- [ ] Séparer la fonction qui permet d'adapter les données ADEME aux mode_id de l'ENTD
- [ ] Ajouter une fonction qui permet de télécharger la dernière version de la base carbone ADEME 
- [ ] Ajouter le fichier excel des modes de l'ENTD (ou lien vers sa source)
- [ ] Passer en fichier excel, les fichiers mapping et custom afin de permettre à l'utilisateur d'adapter ses FE ?

**Comment by louisegontier** [comment]
Petite MAJ de la fonction
Comment permettre à l'utilisateur de changer le fichier de mapping ou d'ajouter une nouvelle version de la base carbone s'il utilise en package ? En passant les dataframe en attribut du trip sampler ?

**Comment by FlxPo** [comment]
Est ce qu'on pourrait utiliser l'API de la base carbone directement pour éviter d'avoir à internaliser ces données ? https://api.gouv.fr/les-api/api_base_carbone

On ne garderait dans Mobility qu'une identification des facteurs d'émissions utiles dans la base carbone (à modifier éventuellement s'il y a une nouvelle version) et des fonctions de requête de l'API.

**Comment by FlxPo** [comment]
J'ai commencé à ajouter les fonctions qui permettent de récupérer les facteurs d'émissions directement depuis l'API de la base carbone, dans https://github.com/mobility-team/mobility/commit/8a70db56f6f3e0f0fea0aff00e876527fe5c56b6. On essaie de se tenir à la stratégie d'utilisation de sources externes définie ici : https://github.com/mobility-team/mobility/issues/23.

Il me reste à  adapter la fonction carbon_computation.

**Comment by FlxPo** [comment]
Ajout d'un test pour la fonction de requête de l'API ADEME, et suppression de la dépendance à ratelimiter (le package n'est plus maintenu et renvoie des deprecation warnings) : https://github.com/mobility-team/mobility/commit/82f53bb985bf4d2293d514b9fcdd8efe99cc7920.

**Comment by Mind-the-Cap** [comment]
`carbon` a été mergée, j'ai fait une [issue spécifique pour l'usage de l'API](https://github.com/mobility-team/mobility/issues/61), je clos :)
