### ISSUE TITLE
[Suggestion] Utiliser PEP8 pour améliorer la lisibilité du code

### ISSUE THREAD

**Issue by Mind-the-Cap** [mobility-team/mobility#20]
Bonjour,

Les conventions Python permettent d'avoir une meilleure lisibilité du code, ce qui est important car on lit plus souvent le code qu'on ne l'écrit (et ça me semble particulièrement vrai avec Mobility). Un code standard peut être réutilisé facilement pour des projets, est plus facile à améliorer, et évite les doublons.

Je vous propose de suivre les conventions [PEP8](https://peps.python.org/pep-0008/) et [PEP257](https://peps.python.org/pep-0257/) pour le projet. Vous trouverez un court descriptif de la première [ici](https://python.doctor/page-pep-8-bonnes-pratiques-coder-python-apprendre), mais voici les points essentiels :
* des lignes courtes (pas plus de 79 caractères),
* indentation avec 4 caractères,
* bon positionnement des espaces,
* commenter le code en anglais,
* utiliser les docstrings (vu la complexité du code, je dirais plutôt la version en plusieurs lignes, en précisant bien les types des données d'entrée pour les fonctions).

La plupart des éditeurs Python proposent de tester la conformité directement en écrivant du code. Pour ce qui est de l'existant, on peut utiliser des solutions comme [black](https://pypi.org/project/black/) qui permettent de le transformer automatiquement (je peux m'en charger si vous le voulez).

N'hésitez pas si vous avez des commentaires ou des remarques !

**Comment by FlxPo** [comment]
Je vote également pour l'utilisation de black, pour être sûr que tout est OK.

**Comment by FlxPo** [comment]
Conversion du code existant dans la branche main avec black : https://github.com/mobility-team/mobility/commit/07786bee128e23c172ddd2df5efd641a9d02385a

J'ai suivi les instructions données par [black](https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html), en identifiant le commit de migration dans un [fichier](https://github.com/mobility-team/mobility/blob/main/.git-blame-ignore-revs).

Comment est ce qu'on fait en sorte d'avoir du code bien formaté dans chaque pull request ? Une check list ? Un action Hithub automatique ?

**Comment by Mind-the-Cap** [comment]
Super !

Je dirais plutôt une action Github, j'ai configuré ça et ça a l'air de bien marcher : https://github.com/mobility-team/mobility/pull/25

**Comment by Mind-the-Cap** [comment]
Ajouté dans la documentation avec https://github.com/mobility-team/mobility/pull/65
