### ISSUE TITLE
Les liens utilisés par get_insee_data et prepare_job_active_population ne sont plus corrects

### ISSUE THREAD

**Issue by FlxPo** [mobility-team/mobility#22]
Les fonctions prepare_facilities et prepare_job_active_population téléchargent des fichiers zip directement depuis le site de l'INSEE. Problème, les url INSEE sont instables, donc les fonctions ne sont plus à jour assez rapidement.

Nous pouvons faire comme les données des enquêtes mobilité, et stocker les données nous même sur data.gouv.fr (https://www.data.gouv.fr/fr/organizations/mobility/) ? Sauf si on trouve une API stable quelque part ?

Les deux fonctions concernées sont ici :
- https://github.com/mobility-team/mobility/blob/cae504c7de9466ecd7c9d9d2f7183fc64debc79d/mobility/parsers/job_active_population.py#L27
- https://github.com/mobility-team/mobility/blob/cae504c7de9466ecd7c9d9d2f7183fc64debc79d/mobility/parsers/permanent_db_facilities.py#L45

**Comment by FlxPo** [comment]
Ajout de la base de données des équipements 2021 sur datagouv : https://www.data.gouv.fr/fr/datasets/equipements-geolocalises-commerce-services-sante-en-2021/

**Comment by Mind-the-Cap** [comment]
Cela me semble effectivement une bonne idée de stocker les données sur data.gouv.fr (je n'ai pas connaissance d'une API stable), mais nous devrions probablement améliorer les métadonnées dans ce cas.
Qui détient les clés du compte ? Idéalement, ça ne devrait pas être une seule personne.

**Comment by FlxPo** [comment]
J'ai ajouté les données nécessaires aux différentes fonctions sur la page du projet : https://www.data.gouv.fr/fr/organizations/mobility/. J'en ai profité pour adapter le code pour utiliser directement les données du recensement 2019 au lieu de 2018.

Il faut que l'on décide d'une stratégie d'utilisation de fichiers externes dans notre code: 
- Inclure systématiquement les fichiers nécessaires pour faire tourner les fonctions et les exemples ?
- Définir des jeux de données "de base" et d'autres qu'on laisse l'utilisateur gérer ?
- Intégrer ou non la mise à jour des jeux de données (millésimes du recensement INSEE par exemple) ?

@Mind-the-Cap est ce que tu as un compte data.gouv.fr ? De manière générale il faut qu'on définisse des rôles plus précis pour  le projet avec différents niveaux de droits.

**Comment by AyoubFOUNDOU** [comment]
Bonjour,
On a utilisé le nouveau lien [(Nouveau lien),](https://www.data.gouv.fr/fr/datasets/r/cbb7be1d-ad09-4813-99c0-598ebd8be305),  sauf que les colonnes du fichier CSV ne sont pas les mêmes comme dans l'ancien fichier (qui est dans le code par défaut). Donc ceci génère des erreurs lors de l'exécution du code **exemple_CCMGC.py**.

**Comment by Mind-the-Cap** [comment]
@FlxPo j'ai un compte datagouv avec mon adresse AREP.

J'ai créé deux issues pour les rôles et la stratégie !

**Comment by FlxPo** [comment]
Je viens de te donner le rôle d'admin pour l'organisation Mobility sur data.gouv.fr. Dis moi si c'est le bon compte, il y en avait deux mais je ne pouvais pas voir l'adresse email utilisée.

**Comment by Mind-the-Cap** [comment]
C'était le bon :)

**Comment by FlxPo** [comment]
@AyoubFOUNDOU je viens de fusionner la branche avec l'exemple de Millau corrigé, qui contient le code avec les bons liens vers les fichiers INSEE (maintenant hébergés sur data gouv). Normalement tout est OK.

Je ferme cette issue pour le moment, continuons à discuter de ce sujet global de l'hébergement des données ici : https://github.com/mobility-team/mobility/issues/23.
