### ISSUE TITLE
[Projet] Définir une stratégie de test

### ISSUE THREAD

**Issue by FlxPo** [mobility-team/mobility#27]
Il faut que l'on ajoute des tests à notre code, pour bien encadrer les modifications du code existant. Cela deviendra d'autant plus nécessaire que le code gagne en complexité.

- @Mind-the-Cap, est ce que tu aurais des conseils pour mettre en place des tests pour le projet ?
- Est ce qu'on se donne un objectif de "coverage" ?
- Est ce qu'on met en place une github action automatisée via codecov (gratuit pour les projets open source) ?

Quelques éléments intéressants ici : https://about.codecov.io/blog/the-10-commandments-of-writing-good-software-tests/

J'ai écrit un premier test ici pour se lancer : https://github.com/mobility-team/mobility/blob/carbon/test/parsers/test_ademe_base_carbone_api.py

**Comment by Mind-the-Cap** [comment]
La coverage est à 95 %, les tests passent et ont bien été automatisés !
